# Netlify config for AutoGPT docs

[build]
  publish = "public/"
  command = "python ../scripts/generate_user_config_docs.py && mkdocs build -d public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../CONTRIBUTING.md ../CODE_OF_CONDUCT.md"
