name: Algorithms Benchmarks

on:
  push:
    paths:
      - 'algorithms/**'
      - 'benchmarks/**'
      - '.github/workflows/algorithms-benchmark.yml'
  pull_request:
    paths:
      - 'algorithms/**'
      - 'benchmarks/**'
      - '.github/workflows/algorithms-benchmark.yml'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-benchmark
      - name: Run sorting benchmarks
        run: |
          PYTHONPATH=. pytest benchmarks/test_sorting_benchmark.py --benchmark-json=benchmarks/results/sorting_current.json -q
          python benchmarks/compare_benchmarks.py benchmarks/results/sorting.json benchmarks/results/sorting_current.json
      - name: Run graph benchmarks
        run: |
          PYTHONPATH=. pytest benchmarks/test_graph_benchmark.py --benchmark-json=benchmarks/results/graph_current.json -q
          python benchmarks/compare_benchmarks.py benchmarks/results/graph.json benchmarks/results/graph_current.json
