name: Documentation CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development, release-* ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Generate configuration reference
        run: |
          python scripts/generate_user_config_docs.py --output docs/configuration.md docs/AutoGPT/configuration/user_configurable.md
          git diff --exit-code docs/configuration.md docs/AutoGPT/configuration/user_configurable.md

      - name: Build documentation
        run: |
          mkdocs build -f docs/mkdocs.yml
